### PR TITLE
Add native LDA function

### PR DESCRIPTION
**Pull request by koheiw**
Address #30

### CODE REVIEW

**Comment by koheiw** [comment]
If you see the code of topicmodels, you will understand why. I also though that its implementation of seeded LDA is wrong. However, I am happy to make this a separate package.

**Comment by kbenoit** [comment]
I have seen it and it's a mess, so is the package. We could offer a simpler approach, so I didn't want to give the impression that I am totally against it, just aware of some challenges. Can we meet those challenges by simplifying the post-estimation functions in a simpler, quanteda-like way, and/or allow them to work with those already found in another package such as **stm**, or the excellent **LDAvis**?

**Comment by koheiw** [comment]
No worries. I was aware that topicmodels has the seeded LDA. This is exactly why I chose LDAGibbs++ here. I am only interested semisupervided LDA so unsupervised LDA is just an by product. The library has many more functions for online training and prediction on new data, but you remained me that I have to work a lot to add functions that I have no plan to use if I add the code to this package. This is why I am happy to put that in my seededlda package (which is currently depends on topicmodels).

**Comment by kbenoit** [comment]
Ah, users, we love them but they always ask for more. https://github.com/bstewart/stm/issues

**Comment by koheiw** [comment]
We don't have enough resources to maintain so many functions, so we need let users to develop the packages via PR. This is why I think modularization is urgently needed.

**Comment by JBGruber** [comment]
Maybe it would be an option to participate in the [Hacktoberfest event](https://hacktoberfest.digitalocean.com/). I tried to participate last year but there were almost no `R` issues around to solve.

**Comment by koheiw** [comment]
@JBGruber can you tell how we can make you (or people like you) feel like to contribute **quanteda.textmodels** or **quanteda** actively?

**Comment by JBGruber** [comment]
I think the Hacktoberfest guidelines for maintainers are a pretty good starting point to get people to contribute actively:

- Apply the "Hacktoberfest" label to issues in your GitHub project that are ready for contributors to work on. (**Since they advertise the event and collect all issues with the label centrally, people who otherwise wouldn't go to the issues page will see it. If you don't want to participate in that or in the 11 month of the year when the event is not on, you could simply share a [link to all quanteda issues with the help wanted label](https://github.com/quanteda/quanteda/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) (which is currently none)**)
- Add a CONTRIBUTING.md file with contribution guidelines to your repository. (**The [quanteda wiki](https://github.com/quanteda/quanteda/wiki) is already pretty but might need some adaption for people who just started developing functions (?)**)
- Choose issues that have a well-defined scope and are self-contained. (**This would probably be the most important thing for me personally. Looking through a few issues it is sometimes not quite clear where to even start especially with functions being moved etc**)
- Adopt a code of conduct to foster a greater sense of inclusion and community. (**You already nailed that one - although it's only in the quanteda package itself so far**)

So I think to get people to help you would have to communicate that you want help and for what specifically. That's why I brought up the Hacktoberfest. But you could also, for example, organise a quanteda-hackaton to solve a long list of issues at once to get things going. I would show up :wink:

**Pull request closed without merging**
